obstacles:
  - id: "base"
    frame_id: "base_link"
    dimensions: [1.0, 0.72, 0.35]
    pose:
      position:
        x: 0.4
        y: 0.0
        z: -0.2
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "husky_cage_front"
    frame_id: "base_link"
    dimensions: [0.01, 0.72, 0.4]
    pose:
      position:
        x: 0.95
        y: 0.0
        z: -0.15
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "husky_cage_back"
    frame_id: "base_link"
    dimensions: [0.01, 0.72, 0.4]
    pose:
      position:
        x: -0.15
        y: 0.0
        z: -0.15
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "husky_cage_left"
    frame_id: "base_link"
    dimensions: [1.0, 0.01, 0.4]
    pose:
      position:
        x: 0.4
        y: 0.4
        z: -0.15
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "husky_cage_right"
    frame_id: "base_link"
    dimensions: [1.0, 0.01, 0.4]
    pose:
      position:
        x: 0.4
        y: -0.4
        z: -0.15
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "control_box"
    frame_id: "base_link"
    dimensions: [0.32, 0.52, 0.4]
    pose:
      position:
        x: 0.69
        y: 0.0
        z: 0.15
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "desk"
    frame_id: "base_link"
    dimensions: [0.75, 1.19, 0.75]
    pose:
      position:
        x: -0.825
        y: 0.0
        z: 0.035
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "box1"
    frame_id: "base_link"
    dimensions: [0.08, 0.08, 0.2]
    pose:
      position:
        x: -0.59
        y: -0.2
        z: 0.485
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "box2"
    frame_id: "base_link"
    dimensions: [0.08, 0.08, 0.25]
    pose:
      position:
        x: -0.59
        y: -0.067
        z: 0.51
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "box3"
    frame_id: "base_link"
    dimensions: [0.08, 0.08, 0.2]
    pose:
      position:
        x: -0.59
        y: 0.067
        z: 0.485
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "box4"
    frame_id: "base_link"
    dimensions: [0.08, 0.08, 0.2]
    pose:
      position:
        x: -0.59
        y: 0.2
        z: 0.485
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "box5"
    frame_id: "base_link"
    dimensions: [0.35, 0.19, 0.14]
    pose:
      position:
        x: -0.625
        y: 0.41
        z: 0.46
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

