obstacles:
  - id: "base"
    frame_id: "base_link"
    dimensions: [0.72, 1.0, 0.35]
    pose:
      position:
        x: 0.0
        y: -0.35
        z: -0.175
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "control_box"
    frame_id: "base_link"
    dimensions: [0.52, 0.32, 0.4]
    pose:
      position:
        x: 0.0
        y: -0.64
        z: 0.2
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "desk"
    frame_id: "base_link"
    dimensions: [1.19, 0.75, 0.735]
    pose:
      position:
        x: 0.0
        y: 0.875
        z: 0.0175
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "box1"
    frame_id: "base_link"
    dimensions: [0.08, 0.08, 0.2]
    pose:
      position:
        x: -0.2
        y: 0.64
        z: 0.485
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "box2"
    frame_id: "base_link"
    dimensions: [0.08, 0.08, 0.25]
    pose:
      position:
        x: -0.067
        y: 0.64
        z: 0.51
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "box3"
    frame_id: "base_link"
    dimensions: [0.08, 0.08, 0.2]
    pose:
      position:
        x: 0.067
        y: 0.64
        z: 0.485
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "box4"
    frame_id: "base_link"
    dimensions: [0.08, 0.08, 0.2]
    pose:
      position:
        x: 0.2
        y: 0.64
        z: 0.485
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - id: "box5"
    frame_id: "base_link"
    dimensions: [0.19, 0.35, 0.12]
    pose:
      position:
        x: 0.41
        y: 0.675
        z: 0.481
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

