poses:
  - x: 0.6
    y: -0.2
    z: 0.685
    roll: 0.0
    pitch: 1.57
    yaw: 0.0
  - x: 0.7
    y: -0.2
    z: 0.685
    roll: 0.0
    pitch: 1.57
    yaw: 0.0
  - x: 0.7
    y: -0.2
    z: 0.75
    roll: 0.0
    pitch: 1.57
    yaw: 0.0
