poses:
  - x: -0.4
    y: 0.067
    z: 0.485
    roll: 3.14
    pitch: 1.57
    yaw: 0.0
  - x: -0.45
    y: 0.067
    z: 0.485
    roll: 3.14
    pitch: 1.57
    yaw: 0.0
  - x: -0.45
    y: 0.067
    z: 0.75
    roll: 3.14
    pitch: 1.57
    yaw: 0.0
  - x: -0.45
    y: 0.2
    z: 0.75
    roll: 3.14
    pitch: 1.57
    yaw: 0.0
  - x: -0.45
    y: 0.2
    z: 0.485
    roll: 3.14
    pitch: 1.57
    yaw: 0.0
  - x: -0.4
    y: 0.2
    z: 0.485
    roll: 3.14
    pitch: 1.57
    yaw: 0.0

