poses:
  - x: -0.3
    y: 0.2
    z: 0.55
    roll: -1.57
    pitch: 0.0
    yaw: 0.0
  - x: -0.3
    y: 0.27
    z: 0.55
    roll: -1.57
    pitch: 0.0
    yaw: 0.0
  - x: -0.3
    y: 0.27
    z: 0.85
    roll: -1.57
    pitch: 0.0
    yaw: 0.0
  - x: 0.0
    y: 0.27
    z: 0.85
    roll: -1.57
    pitch: 0.0
    yaw: 0.0
  - x: 0.0
    y: 0.27
    z: 0.55
    roll: -1.57
    pitch: 0.0
    yaw: 0.0
  - x: 0.0
    y: 0.2
    z: 0.55
    roll: -1.57
    pitch: 0.0
    yaw: 0.0

