poses:
  - x: -0.3
    y: -0.067
    z: 0.485
    roll: 0.0
    pitch: 1.57
    yaw: 0.0
  # - x: -0.4
  #   y: -0.067
  #   z: 0.485
  #   roll: 1.57
  #   pitch: 0.0
  #   yaw: 1.57
  # - x: -0.4
  #   y: -0.067
  #   z: 0.75
  #   roll: 1.57
  #   pitch: 0.0
  #   yaw: 1.57


